#!/usr/bin/env node
// One-shot generator: questions.js -> supabase/migrations/..._seed_lessons_questions.sql
// Deterministic uuidv5 ids (lesson date / lesson date + position), so re-running
// is byte-stable. Dedupe safeguard: identical prompt, or same type + same
// normalized first answer, across lessons -> the OLDER entry seeds inactive.
"use strict"
const fs = require("fs")
const crypto = require("crypto")
const path = require("path")

const NAMESPACE_URL = "6ba7b811-9dad-11d1-80b4-00c04fd430c8" // RFC 4122

function uuid5(name) {
    const ns = Buffer.from(NAMESPACE_URL.replace(/-/g, ""), "hex")
    const h = crypto.createHash("sha1")
        .update(Buffer.concat([ns, Buffer.from(name, "utf8")])).digest()
    const b = Buffer.from(h.subarray(0, 16))
    b[6] = (b[6] & 0x0f) | 0x50 // version 5
    b[8] = (b[8] & 0x3f) | 0x80 // RFC variant
    const x = b.toString("hex")
    return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20)}`
}

const lessonId = d => uuid5(`https://bromodachi.local/lesson/${d}`)
const questionId = (d, pos) => uuid5(`https://bromodachi.local/q/${d}/${pos}`)

// Walk questions.js line by line: lesson marker comments set the current
// lesson; single-line object literals are entries, evaluated by the JS
// engine itself so every escape is handled exactly as QML handled it.
const src = fs.readFileSync(path.join(__dirname, "..", "questions.js"), "utf8")
const lessons = new Map() // date -> [entry]
let current = null
for (const line of src.split("\n")) {
    const m = line.match(/\/\/ --- lesson (\d{4}-\d{2}-\d{2})/)
    if (m) { current = m[1]; if (!lessons.has(current)) lessons.set(current, []); continue }
    const t = line.trim()
    if (current && t.startsWith("{ type:")) {
        const entry = eval("(" + t.replace(/,\s*$/, "") + ")")
        lessons.get(current).push(entry)
    }
}

const dates = [...lessons.keys()].sort()
const norm = s => s.replace(/[\s　]+/g, "").toLowerCase()

// dedupe safeguard (newest survives): scan newest -> oldest
const seen = new Map() // key -> lesson date that claimed it
for (const d of [...dates].reverse()) {
    for (const e of lessons.get(d)) {
        e.active = true
        for (const key of [`p:${e.prompt}`, `a:${e.type}:${norm(e.answers[0])}`]) {
            const claimed = seen.get(key)
            if (claimed && claimed !== d) e.active = false
            else seen.set(key, d)
        }
    }
}

const q = s => "'" + s.replace(/'/g, "''") + "'"
const out = []
out.push("-- Generated by scripts/gen_seed.js from questions.js. Do not hand-edit;")
out.push("-- re-run the generator (byte-stable: deterministic uuidv5 ids).")
out.push("")
for (const d of dates)
    out.push(`insert into lessons (id, taught_on) values (${q(lessonId(d))}, ${q(d)});`)
out.push("")
let total = 0, inactive = 0
for (const d of dates) {
    out.push(`-- lesson ${d} (${lessons.get(d).length} questions)`)
    lessons.get(d).forEach((e, pos) => {
        total++
        if (!e.active) inactive++
        out.push(
            "insert into questions (id, lesson_id, type, prompt, answers, hint, ja, active, position) values (" +
            [q(questionId(d, pos)), q(lessonId(d)), q(e.type), q(e.prompt),
             q(JSON.stringify(e.answers)) + "::jsonb",
             e.hint ? q(e.hint) : "null",
             e.ja === false ? "false" : "true",
             e.active ? "true" : "false",
             String(pos)].join(", ") + ");")
    })
    out.push("")
}
const dest = path.join(__dirname, "..", "supabase", "migrations", "20260901120200_seed_lessons_questions.sql")
fs.writeFileSync(dest, out.join("\n"))
console.log(`lessons: ${dates.map(d => `${d}=${lessons.get(d).length}`).join("  ")}`)
console.log(`total ${total}, inactive-by-dedupe ${inactive}, wrote ${path.relative(process.cwd(), dest)}`)
